steps:

  - simple_align:
      cases: false
      top_level_patterns: false
      records: false

  - imports:
      align: none
      list_align: after_alias
      long_list_align: new_line
      empty_list_align: inherit
      list_padding: 2
      separate_lists: true

  - language_pragmas:
      style: compact
      align: false
      remove_redundant: true

  - tabs:
      spaces: 2

  - trailing_whitespace: {}

columns: 80

newline: lf
