sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- (cd haskell && stack --no-nix --no-terminal setup)
- (cd haskell && stack --no-nix --no-terminal --skip-ghc-check test :Fast)
- (cd haskell && stack --no-nix --no-terminal haddock)
- cp -r haskell/.stack-work/install/x86_64-linux/lts-5.2/7.10.3/doc .out/haskell
- .out/deploy.sh

addons:
  apt:
    packages:
    - libgmp-dev
