sudo: false

cache:
  directories:
  - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- .travis/stack.sh setup
- .travis/stack.sh --skip-ghc-check test :Fast
- .travis/stack.sh haddock
- cp -r haskell/.stack-work/install/x86_64-linux/lts-5.2/7.10.3/doc site/haskell
- ./site-deploy.sh

addons:
  apt:
    packages:
    - libgmp-dev
