sudo: false

cache:
  directories:
  - $HOME/.stack
  - $HOME/.ivy2

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- .travis/stack.sh setup
- .travis/stack.sh install hscolour
- .travis/stack.sh --skip-ghc-check test
- .travis/sbt.sh test:run
- .travis/sbt.sh test
- .travis/stack.sh haddock
- .travis/sbt.sh doc
- cp -r $(cd haskell; stack path --local-doc-root) site/haskell
- cp -r scala/target/scala-2.11/api site/scala
- if [ $TRAVIS_BRANCH = "master" ]; then ./site-deploy.sh; fi

addons:
  apt:
    packages:
    - libgmp-dev
    - oracle-java8-installer

notifications:
  email: false
